language: python

python:
    - "3.5"
    - "3.6"
addons:
  postgresql: "10"
 
services:
    - postgresql

install:
    - python setup.py -q install
    - pip install coverage coveralls

script: coverage run --rcfile=.coveragerc setup.py test

after_success:
    - coveralls
